### ISSUE TITLE
Make site-nav and game-nav divs/navs inline with buttons

### ISSUE THREAD

**Issue by AmazingMech2418** [Mountio/Mountio.github.io#11]

**Comment by trafort** [comment]
@WaterfallCoding 
Designing Is our code!
Y+F
YOU ARE FIRED!

**Comment by trafort** [comment]
We don't need a Side nav, 40% of websites slow down with a nav. 
But, we could add it, I'll ask @WaterfallCoding  or @redmangospros  To Make A design model

**Comment by AmazingMech2418** [comment]
OK. I'm talking about services.html in this repo, so It's just formatting. We could change the format though...

**Comment by radioblahaj** [comment]
Yeah Good idea, @trafort
