### ISSUE TITLE
What did you do to the website?

### ISSUE THREAD

**Issue by AmazingMech2418** [Mountio/Mountio.github.io#15]

**Comment by AmazingMech2418** [comment]
WHY DID YOU ADD TRAVIS?!?! THAT JUST DESTROYED SO MUCH OF OUR CODE!

**Comment by radioblahaj** [comment]
It did notyhing

**Comment by AmazingMech2418** [comment]
Nothing? It made me have to fix so many "errors" just because it was part of the repo!

**Comment by radioblahaj** [comment]
Sorry, I let my pal expriment with mountio and github

**Comment by AmazingMech2418** [comment]
OK. I deleted Travis and fixed a lot of bugs.
