### ISSUE TITLE
Give credit to Materialize.css

### ISSUE THREAD

**Issue by Sheshank-s** [Mountio/Mountio.github.io#18]
You used Materialize.css to make the site (Which makes no sense because you are selling sites but ok), and you haven't credited them.

**Comment by radioblahaj** [comment]
We're Not Selling them, and this is our main site, we are in still of process of updating ths, so soon,
we will Credit

**Comment by Sheshank-s** [comment]
Okay, but please explain me one thing. If you are giving websites to people, why would you use Materialize to make your own website? Shouldn't you make a website that you made so people would know the skills of Mountio?

**Comment by radioblahaj** [comment]
We Are Testing A Theme.
And, We do not want to compete With Swiftsites.
So..

**Comment by radioblahaj** [comment]
a60e3b3

**Comment by radioblahaj** [comment]
Closed in a60e3b3

**Comment by AmazingMech2418** [comment]
We should make our own CSS theme for Mountio @redmangospros . @GreenBayRules is right.

**Comment by radioblahaj** [comment]
Actully, Yeah, We Should.
