### ISSUE TITLE
Purpose of Mountio (a question)

### ISSUE THREAD

**Issue by SheepTester** [Mountio/Mountio.github.io#22]
Seeing that Mountio was originally meant to be a competitor to SwiftSites, do the services that Mountio provides include website themes?

**Comment by AmazingMech2418** [comment]
Yes.

**Comment by SheepTester** [comment]
So any of us could contribute by making a website theme?

(I'm asking because I happen to be [working](https://github.com/SheepTester/themes) on a [website theme](https://sheeptester.github.io/themes/billy-goat/), which, sarcastically said, I totally did not start after seeing the existence of Mountio and SwiftSites)

**Comment by radioblahaj** [comment]
So wpuld you mind if we can use it

**Comment by SheepTester** [comment]
Nope, I wouldn't mind :)

**Comment by radioblahaj** [comment]
Would you.mind transfering the repo?

**Comment by SheepTester** [comment]
I'm planning to put other themes that I might keep for myself in the same repository, but perhaps I can just copy the files over or create a copy of the repository

**Comment by radioblahaj** [comment]
Sure.
