### ISSUE TITLE
We need to improve the CSS

### ISSUE THREAD

**Issue by AmazingMech2418** [Mountio/Mountio.github.io#3]

**Comment by radioblahaj** [comment]
tRUE!

**Comment by AmazingMech2418** [comment]
We have to compete with SwiftSites! I just improved the card format.

**Comment by radioblahaj** [comment]
Nice:)

**Comment by AmazingMech2418** [comment]
Thank you!

**Comment by radioblahaj** [comment]
SwiftSites Is So Good..

**Comment by AmazingMech2418** [comment]
I know. Mountio can be better.

**Comment by radioblahaj** [comment]
Hopefully, Happpy new year

**Comment by AmazingMech2418** [comment]
Happy new year!

**Comment by radioblahaj** [comment]
@WaterfallCoding 
What Do you think of our design and css?

**Comment by WaterfallCoding** [comment]
Sorry, I'm not super pro with github - How do I see the files?

**Comment by AmazingMech2418** [comment]
Click on the files in the folder assets. Also, go to mountio.github.io to see the website.

**Comment by AmazingMech2418** [comment]
Wait... I didn't know you were on github. Would you like to join waffle?

**Comment by AmazingMech2418** [comment]
@WaterfallCoding
