### ISSUE TITLE
Mech

### ISSUE THREAD

**Issue by radioblahaj** [Mountio/Mountio.github.io#4]
I need to send you something

**Comment by radioblahaj** [comment]
https://www.canva.com/design/DACrWViXGqQ/xUXXzT3IjcNyFDmTTwtcpw/view?utm_content=DACrWViXGqQ&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by radioblahaj** [comment]
https://www.canva.com/design/DACrWaR8LpU/SjJgtKA66cVoP3jlHHBuVw/view?utm_content=DACrWaR8LpU&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by trafort** [comment]
@amazinigmech2418

**Comment by AmazingMech2418** [comment]
What is this?

**Comment by trafort** [comment]
Marketing

**Comment by radioblahaj** [comment]
Mech
